language: node_js
sudo: false
node_js:
  - "lts/carbon"
cache:
  directories:
    - node_modules
install:
  - npm install -g @ui5/cli
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
